# basic settings


NAME: 'grain'  # config name
COMMENT: 'grain project,. 3 channels...'
AUTHOR: 'dyw'

CHECKPOINTS: "./runs/checkpoints/"        # path to save checkpoints
LOG_PATH: "./runs/logs/"                  # path to save log files
SAVE_ONNX_PATH: "./runs/onnx/"    #path to save onnx file


DATASET:
  PATH: './IEEERA/maize'
  NAME: 'maize_3channel_224x224_0705'

RESUME:
  FLAG: False
  #PATH: 

AUGMENT:
  MIXUP_RATIO: 0
  RandBright_limit: 0.15 
  RandBright_ratio: 0.3 
  RandContra_limit: 0.15
  RandContra_ratio: 0.3


MODEL:
  NAME: 'resnet50'


OPTIM:
  INIT_LR: 1.2e-3
  LR_SCHEDULER: 'step'
  LOSS: 'ce'


TRAIN:
  BATCH: 160
  EPOCHS: 50
  START_EPOCH: 0
  SIZE: (224,224)


TEST:  
  BATCH: 128
  SIZE: (224,224)


